// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

Group Computation(const DTMask2D &mask,int count,int seed,DTRegion1D rRange,
                  DTRegion1D yRange,int rCount,int yCount,int runs);

#endif /* IT_computation_h */ 
