// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

//////////////////////////////////////////////////////////////////////////////
//    Group
//////////////////////////////////////////////////////////////////////////////

// To make it stand-alone put this into the file "Group.h"

#ifndef ITCustomClass_Group
#define ITCustomClass_Group

#include <string>
#include "DTDataStorage.h"
#include "DTImage.h"
#include "DTTable.h"

struct Group {
    DTTable values;
    DTTable L;
    DTTable L2;
    DTImage pdf;
    DTTable sample;

    void pinfo(void) const;
    void pinfoIndent(std::string) const;
    static void WriteStructure(DTDataStorage &,std::string);
};

extern void Write(DTDataStorage &,std::string name,const Group &);
extern void Read(DTDataStorage &,std::string name,Group &);
extern void WriteOne(DTDataStorage &,std::string name,const Group &);
extern DTTable StructureTable(const Group &);


#endif // ITCustomClass_Group

