// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

MyGroup Computation(const DTImage &image,DTPoint2D from,DTPoint2D to,int N,
                    int Width);

#endif /* IT_computation_h */ 
