// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

//////////////////////////////////////////////////////////////////////////////
//    MyGroup
//////////////////////////////////////////////////////////////////////////////

// To make it stand-alone put this into the file "MyGroup.h"

#ifndef ITCustomClass_MyGroup
#define ITCustomClass_MyGroup

#include <string>
#include "DTDataStorage.h"
#include "DTPath2DValues.h"
#include "DTTable.h"

struct MyGroup {
    DTPath2DValues Values;
    double Variation1;
    double ratio;
    double arcForRatio;
    double ratioAtMax;
    double arcForRatioAtMax;

    void pinfo(void) const;
    void pinfoIndent(std::string) const;
    static void WriteStructure(DTDataStorage &,std::string);
};

extern void Write(DTDataStorage &,std::string name,const MyGroup &);
extern void Read(DTDataStorage &,std::string name,MyGroup &);
extern void WriteOne(DTDataStorage &,std::string name,const MyGroup &);
extern DTTable StructureTable(const MyGroup &);


#endif // ITCustomClass_MyGroup

