// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

PeakGroup Computation(const DTSet<DTImage> &combined,int start);

#endif /* IT_computation_h */ 
