// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

//////////////////////////////////////////////////////////////////////////////
//    PeakGroup
//////////////////////////////////////////////////////////////////////////////

// To make it stand-alone put this into the file "PeakGroup.h"

#ifndef ITCustomClass_PeakGroup
#define ITCustomClass_PeakGroup

#include <string>
#include "DTDataStorage.h"
#include "DTImage.h"
#include "DTPoint2D.h"
#include "DTTable.h"

struct PeakGroup {
    double height;
    double base;
    double threshold;
    DTImage peak;
    DTPoint2D center;
    DTTable intensities;

    void pinfo(void) const;
    void pinfoIndent(std::string) const;
    static void WriteStructure(DTDataStorage &,std::string);
};

extern void Write(DTDataStorage &,std::string name,const PeakGroup &);
extern void Read(DTDataStorage &,std::string name,PeakGroup &);
extern void WriteOne(DTDataStorage &,std::string name,const PeakGroup &);
extern DTTable StructureTable(const PeakGroup &);


#endif // ITCustomClass_PeakGroup

