// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

void Computation(const DTMask2D &region,int seed,int count,
                 const DTDictionary &parameters,DTMutableSet<DTTable> &output);

#endif /* IT_computation_h */ 
