// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"
class DTDictionary;
class DTMask2D;
class DTTable;
template <class T> class DTSet;

DTSet<DTTable> Computation(const DTMask2D &region,int seed,int count,
                           const DTDictionary &parameters);

#endif /* IT_computation_h */ 
