// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#include "computation.h"

#include "DTArguments.h"
#include "DTTimer.h"
#include "DTDataFile.h"
#include "DTDictionary.h"
#include "DTDoubleArrayOperators.h"
#include "DTMask2D.h"
#include "DTSet.h"
#include "DTTable.h"
#include "DTUtilities.h"
#include "DTError.h"

int main(int argc,const char *argv[])
{
    DTSetArguments(argc,argv);

    DTDictionary parameters;
    DTMask2D region;
    int seed, count;

    {
        // Inside a scope so that the data files will be closed before the computation starts.
        DTDataFile inputDataFile("Input.dtbin",DTFile::ReadOnly);
        if (inputDataFile.IsOpen()==false) {
            std::cerr << "No input file found. Might have to save input for debugging." << std::endl;
        }

        Read(inputDataFile,"region",region);
        seed = inputDataFile.ReadNumber("seed");
        count = inputDataFile.ReadNumber("count");
        Read(inputDataFile,"parameters",parameters);
    }

    DTDataFile outputFile("Output.dtbin",DTFile::NewReadWrite);

    //DTTimer timer;
    //timer.Start();
    DTSet<DTTable> output = Computation(region,seed,count,parameters);
    //timer.Stop(); // Use timer.Time() to get the elapsed time

    if (DTHowManyErrors()>0) outputFile.Save(DTHowManyErrors(),"ErrorCount"); // For error logging

    WriteOne(outputFile,"Var",output);
    // To speed up reading.
    outputFile.SaveIndex();

    return 0;
}
