// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#include "computation.h"

#include "DTArguments.h"
#include "DTTimer.h"
#include "DTDataFile.h"
#include "DTError.h"

int main(int argc,const char *argv[])
{
    DTSetArguments(argc,argv);

    DTDictionary parameters;
    DTMask2D region;
    int seed, count;

    {
        // Inside a scope so that the data files will be closed before the computation starts.
        DTDataFile inputDataFile("Input.dtbin",DTFile::ReadOnly);
        if (inputDataFile.IsOpen()==false) {
            std::cerr << "No input file found. Might have to save input for debugging." << std::endl;
        }

        Read(inputDataFile,"region",region);
        seed = inputDataFile.ReadNumber("seed");
        count = inputDataFile.ReadNumber("count");
        Read(inputDataFile,"parameters",parameters);
    }

    DTDataFile outputFile("Output.dtbin",DTFile::NewReadWrite);

    DTMutableSet<DTTable> output(outputFile,"Var");
    Computation(region,seed,count,parameters,output);

    if (DTHowManyErrors()>0) outputFile.Save(DTHowManyErrors(),"ErrorCount"); // For error logging

    {
        // Structure information for the set
        std::string baseName = "SeqInfo_Var";
        std::string eName = baseName+"_E";
        std::string pName = baseName+"_P";

        // Structure for parameters
        outputFile.Save("run",pName+"_1N");
        outputFile.Save("Number",pName+"_1T");
        outputFile.Save(1,pName+"_N");

        // Structure for element
        outputFile.Save("time",eName+"_1N");
        outputFile.Save("Number",eName+"_1T");
        outputFile.Save("point",eName+"_2N");
        outputFile.Save("Point2D",eName+"_2T");
        outputFile.Save(2,eName+"_N");
        outputFile.Save("Table",eName);

        outputFile.Save("Table Set","Seq_Var");
    }
    // To speed up reading.
    outputFile.SaveIndex();

    return 0;
}
