// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_structure_h
#define IT_structure_h

#include "DTDictionary.h"
#include "DTDoubleArray.h"
#include "DTIntArray.h"
#include "DTMask2D.h"
#include "DTSet.h"
#include "DTTable.h"


#endif /* IT_structure_h */ 
