// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

DTTable Computation(const DTImage &pdf,double p,const DTMask2D &mask,
                    const DTTable &points);

#endif /* IT_computation_h */ 
