// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

Correlation Computation(const DTImage &image,const DTMask2D &mask);

#endif /* IT_computation_h */ 
