// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#include "structures.h"

//////////////////////////////////////////////////////////////////////////////
//    Correlation
//////////////////////////////////////////////////////////////////////////////

void Correlation::pinfo(void) const
{
    pinfoIndent("");
}

void Correlation::pinfoIndent(std::string pad) const
{
    std::cerr << pad << "coeff = " << coeff << std::endl;
}

void Correlation::WriteStructure(DTDataStorage &output,std::string name)
{
    // Structure for "coeff"
    output.Save("coeff",name+"_1N");
    output.Save("Number",name+"_1T");

    output.Save(1,name+"_N");
    output.Save("Correlation",name+"_Name");
    output.Save("Group",name);
}

void Write(DTDataStorage &output,std::string name,const Correlation &var)
{
    output.Save(var.coeff,name+"_coeff");
    Write(output,name,DTDoubleArray());
}

void WriteOne(DTDataStorage &output,std::string name,const Correlation &var)
{
    Write(output,name,var);
    output.Save("Group","Seq_"+name);
    Correlation::WriteStructure(output,"SeqInfo_"+name);
}

void Read(DTDataStorage &input,std::string name,Correlation &var)
{
    var.coeff = input.ReadNumber(name+"_coeff");
}
