// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

//////////////////////////////////////////////////////////////////////////////
//    Correlation
//////////////////////////////////////////////////////////////////////////////

// To make it stand-alone put this into the file "Correlation.h"

#ifndef ITCustomClass_Correlation
#define ITCustomClass_Correlation

#include <string>
#include "DTDataStorage.h"
#include "DTTable.h"

struct Correlation {
    double coeff;

    void pinfo(void) const;
    void pinfoIndent(std::string) const;
    static void WriteStructure(DTDataStorage &,std::string);
};

extern void Write(DTDataStorage &,std::string name,const Correlation &);
extern void Read(DTDataStorage &,std::string name,Correlation &);
extern void WriteOne(DTDataStorage &,std::string name,const Correlation &);
extern DTTable StructureTable(const Correlation &);


#endif // ITCustomClass_Correlation

