// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

DTPath2D Computation(const DTMask2D &mask,const DTTable &points,int rCount,
                     DTRegion1D rRange);

#endif /* IT_computation_h */ 
