// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_structure_h
#define IT_structure_h

#include "DTDoubleArray.h"
#include "DTIntArray.h"
#include "DTMask2D.h"
#include "DTPath2D.h"
#include "DTRegion1D.h"
#include "DTTable.h"


#endif /* IT_structure_h */ 
