// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

#include "DTDataFile.h"

void Computation(const DTTable &initial,double D,double dt,double until,
                 int stride,double maxVal,double v_max,double k,
                 double fluxOnLeft,
                 DTDataFile &output); // Write all output to this file

#endif /* IT_computation_h */ 
