// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#include "computation.h"

#include "DTArguments.h"
#include "DTTimer.h"
#include "DTDataFile.h"

int main(int argc,const char *argv[])
{
    DTSetArguments(argc,argv);

    DTTable initial;
    double D, dt, until, maxVal, v_max, k, fluxOnLeft;
    int stride;

    {
        // Inside a scope so that the input data file will be closed before the computation is called.
        DTDataFile inputDataFile("Input.dtbin",DTFile::ReadOnly);
        DTDataFile variableDataFile;

        variableDataFile = DTDataFile("initial.dtbin",DTFile::ReadOnly);
        Read(variableDataFile,"initial",initial);
        D = inputDataFile.ReadNumber("D");
        dt = inputDataFile.ReadNumber("dt");
        until = inputDataFile.ReadNumber("until");
        stride = inputDataFile.ReadNumber("stride");
        maxVal = inputDataFile.ReadNumber("maxVal");
        v_max = inputDataFile.ReadNumber("v_max");
        k = inputDataFile.ReadNumber("k");
        fluxOnLeft = inputDataFile.ReadNumber("fluxOnLeft");
    }

    // Create the output file.
    DTDataFile outputFile("Output.dtbin",DTFile::NewReadWrite);
    //DTTimer timer;
    //timer.Start();
    Computation(initial,D,dt,until,stride,maxVal,v_max,k,fluxOnLeft,
                outputFile); // Write all output to this file

    //timer.Stop(); // Use timer.Time() to get the elapsed time

    // To speed up reading.
    outputFile.SaveIndex();

    return 0;
}
