// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"
class DTImage;
class DTTable;
template <class T> class DTSet;

DTSet<DTImage> Computation(const DTSet<DTImage> &input,const DTTable &points,
                           double time,double before,double after,double width);

#endif /* IT_computation_h */ 
