// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#include "computation.h"

#include "DTArguments.h"
#include "DTTimer.h"
#include "DTDataFile.h"
#include "DTDoubleArrayOperators.h"
#include "DTImage.h"
#include "DTSet.h"
#include "DTTable.h"
#include "DTUtilities.h"
#include "DTError.h"

int main(int argc,const char *argv[])
{
    DTSetArguments(argc,argv);

    DTSet<DTImage> input;
    DTTable points;
    double time, before, after, width;

    {
        // Inside a scope so that the data files will be closed before the computation starts.
        DTDataFile inputDataFile("Input.dtbin",DTFile::ReadOnly);
        if (inputDataFile.IsOpen()==false) {
            std::cerr << "No input file found. Might have to save input for debugging." << std::endl;
        }
        DTDataFile variableDataFile;

        variableDataFile = DTDataFile("input_2.dtbin",DTFile::ReadOnly);
        Read(variableDataFile,"input",input);
        variableDataFile = DTDataFile("points.dtbin",DTFile::ReadOnly);
        Read(variableDataFile,"points",points);
        time = inputDataFile.ReadNumber("time");
        before = inputDataFile.ReadNumber("before");
        after = inputDataFile.ReadNumber("after");
        width = inputDataFile.ReadNumber("width");
    }

    DTDataFile outputFile("Output.dtbin",DTFile::NewReadWrite);

    //DTTimer timer;
    //timer.Start();
    DTSet<DTImage> output = Computation(input,points,time,before,after,width);
    //timer.Stop(); // Use timer.Time() to get the elapsed time

    if (DTHowManyErrors()>0) outputFile.Save(DTHowManyErrors(),"ErrorCount"); // For error logging

    WriteOne(outputFile,"Var",output);
    // To speed up reading.
    outputFile.SaveIndex();

    return 0;
}
