// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

DTTable Computation(const DTTable &from,const DTTable &to,
                    const DTMask2D &inside);

#endif /* IT_computation_h */ 
