// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

void DoG(const DTImage &image,double sigma,int inOctave,int numOctaves,
         DTMutableSet<DTImage> &output);

#endif /* IT_computation_h */ 
