// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

DTImage GaussianFilter(const DTImage &image,double sigma);

#endif /* IT_computation_h */ 
