// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_structure_h
#define IT_structure_h

#include "DTDoubleArray.h"
#include "DTImage.h"
#include "DTIntArray.h"


#endif /* IT_structure_h */ 
