// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

void Computation(const DTSet<DTImage> &images,const DTTable &parameters,
                 int width,double t,DTMutableSet<DTImage> &output);

#endif /* IT_computation_h */ 
