// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"
class DTImage;
class DTTable;
template <class T> class DTSet;

DTSet<DTImage> Computation(const DTSet<DTImage> &images,int width,double t,
                           const DTTable &parameters);

#endif /* IT_computation_h */ 
