// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"
class DTDictionary;
class DTImage;
template <class T> class DTSet;

Group Computation(const DTSet<DTImage> &images,int ptNumber,
                  const DTDictionary &parameters);

#endif /* IT_computation_h */ 
