// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

//////////////////////////////////////////////////////////////////////////////
//    Group
//////////////////////////////////////////////////////////////////////////////

// To make it stand-alone put this into the file "Group.h"

#ifndef ITCustomClass_Group
#define ITCustomClass_Group

#include <string>
#include "DTDataStorage.h"
#include "DTFunction1D.h"
#include "DTTable.h"

struct Group {
    double average;
    double width;
    DTTable histogram;
    DTFunction1D fit;
    double R2;
    double delay;
    double decay;
    double shift;
    DTTable Drift;
    DTTable Piecewise_Fit;
    DTTable pointsUsedForFit;

    void pinfo(void) const;
    void pinfoIndent(std::string) const;
    static void WriteStructure(DTDataStorage &,std::string);
};

extern void Write(DTDataStorage &,std::string name,const Group &);
extern void Read(DTDataStorage &,std::string name,Group &);
extern void WriteOne(DTDataStorage &,std::string name,const Group &);
extern DTTable StructureTable(const Group &);


#endif // ITCustomClass_Group

