// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

MyGroup Computation(const DTTable &extrema,const DTImage &magnitude,
                    double distance,double threshold);

#endif /* IT_computation_h */ 
