// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#include "computation.h"

#include "DTArguments.h"
#include "DTTimer.h"
#include "DTDataFile.h"
#include "DTError.h"

int main(int argc,const char *argv[])
{
    DTSetArguments(argc,argv);

    DTImage magnitude;
    DTTable extrema;
    double distance, threshold;

    {
        // Inside a scope so that the data files will be closed before the computation starts.
        DTDataFile inputDataFile("Input.dtbin",DTFile::ReadOnly);
        if (inputDataFile.IsOpen()==false) {
            std::cerr << "No input file found. Might have to save input for debugging." << std::endl;
        }
        DTDataFile variableDataFile;

        variableDataFile = DTDataFile("extrema.dtbin",DTFile::ReadOnly);
        Read(variableDataFile,"extrema",extrema);
        variableDataFile = DTDataFile("magnitude.dtbin",DTFile::ReadOnly);
        Read(variableDataFile,"magnitude",magnitude);
        distance = inputDataFile.ReadNumber("distance");
        threshold = inputDataFile.ReadNumber("threshold");
    }

    DTDataFile outputFile("Output.dtbin",DTFile::NewReadWrite);

    //DTTimer timer;
    //timer.Start();
    MyGroup output = Computation(extrema,magnitude,distance,threshold);

    //timer.Stop(); // Use timer.Time() to get the elapsed time
    if (DTHowManyErrors()>0) outputFile.Save(DTHowManyErrors(),"ErrorCount"); // For error logging

    WriteOne(outputFile,"Var",output);
    // To speed up reading.
    outputFile.SaveIndex();

    return 0;
}
