// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"
class DTDictionary;
class DTImage;
class DTTable;
template <class T> class DTSet;

DTSet<DTImage> Computation(const DTSet<DTImage> &everything,
                           const DTTable &spots,double time,int timeback,
                           int timeforward,const DTDictionary &parameters);

#endif /* IT_computation_h */ 
