// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

void Computation(const DTSet<DTImage> &everything,const DTTable &spots,double time,int timeback,
                 int timeforward,double pixels,DTMutableSet<DTImage> &output);

#endif /* IT_computation_h */ 
