// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

DipoleInfo Computation(const DTImage &image);

#endif /* IT_computation_h */ 
