// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#include "computation.h"

#include "DTArguments.h"
#include "DTTimer.h"
#include "DTDataFile.h"
#include "DTError.h"

int main(int argc,const char *argv[])
{
    DTSetArguments(argc,argv);

    DTImage image;

    {
        // Inside a scope so that the data files will be closed before the computation starts.
        DTDataFile variableDataFile;

        variableDataFile = DTDataFile("image.dtbin",DTFile::ReadOnly);
        Read(variableDataFile,"image",image);
    }

    DTDataFile outputFile("Output.dtbin",DTFile::NewReadWrite);

    //DTTimer timer;
    //timer.Start();
    MyGroup output = Computation(image);
    //timer.Stop(); // Use timer.Time() to get the elapsed time

    if (DTHowManyErrors()>0) outputFile.Save(DTHowManyErrors(),"ErrorCount"); // For error logging

    WriteOne(outputFile,"Var",output);
    // To speed up reading.
    outputFile.SaveIndex();

    return 0;
}
