// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_structure_h
#define IT_structure_h

#include "DTDataStorage.h"
#include "DTDoubleArray.h"
#include "DTImage.h"
#include "DTIntArray.h"
#include "DTPoint2D.h"


#include "DipoleInfo.h"
/* Commented out because the 'Autogenerate class' button in the Group definition is not selected.

   Intended for cases where this is defined elsewhere (e.g. code shared by multiple projects)

   In this case the class has to be defined in the above header file
 and is not created automatically by ImageTank.

   Can use the below code block to update that shared definition.

//////////////////////////////////////////////////////////////////////////////
//    DipoleInfo
//////////////////////////////////////////////////////////////////////////////

struct DipoleInfo {
    DTImage input;
    DTImage first_peak;
    DTImage first_residual;
    DTImage second_peak;
    DTImage second_residual;
    DTPoint2D first_center;
    double first_base;
    double first_height;
    DTPoint2D second_center;
    double second_base;
    double second_height;
    double distance;
    double R2first;
    double RMSEfirst;
    double R2second;
    double RMSEsecond;
    double flagFirst;
    double flagSecond;
    double ratio;

    void pinfo(void) const;
    void pinfoIndent(std::string) const;
    static void WriteStructure(DTDataStorage &,std::string);
};

extern void Write(DTDataStorage &,std::string name,const DipoleInfo &);
extern void Read(DTDataStorage &,std::string name,DipoleInfo &);
extern void WriteOne(DTDataStorage &,std::string name,const DipoleInfo &);

*/ 

#endif /* IT_structure_h */ 
