// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_structure_h
#define IT_structure_h

#include "DTDataStorage.h"
#include "DTDoubleArray.h"
#include "DTImage.h"
#include "DTIntArray.h"
#include "DTPoint2D.h"


//////////////////////////////////////////////////////////////////////////////
//    MyGroup
//////////////////////////////////////////////////////////////////////////////

struct MyGroup {
    DTImage input;
    DTImage first_peak;
    DTImage first_residual;
    DTImage second_peak;
    DTImage second_residual;
    DTPoint2D first_center;
    double first_base;
    double first_height;
    DTPoint2D second_center;
    double second_base;
    double second_height;
    double distance;

    void pinfo(void) const;
    void pinfoIndent(std::string) const;
    static void WriteStructure(DTDataStorage &,std::string);
};

extern void Write(DTDataStorage &,std::string name,const MyGroup &);
extern void Read(DTDataStorage &,std::string name,MyGroup &);
extern void WriteOne(DTDataStorage &,std::string name,const MyGroup &);

#endif /* IT_structure_h */ 
