// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#include "structures.h"

//////////////////////////////////////////////////////////////////////////////
//    MyGroup
//////////////////////////////////////////////////////////////////////////////

void MyGroup::pinfo(void) const
{
    pinfoIndent("");
}

void MyGroup::pinfoIndent(std::string pad) const
{
    std::cerr << pad << "input = "; input.pinfo();
    std::cerr << pad << "first_peak = "; first_peak.pinfo();
    std::cerr << pad << "first_residual = "; first_residual.pinfo();
    std::cerr << pad << "second_peak = "; second_peak.pinfo();
    std::cerr << pad << "second_residual = "; second_residual.pinfo();
    std::cerr << pad << "first_center = "; first_center.pinfo();
    std::cerr << pad << "first_base = " << first_base << std::endl;
    std::cerr << pad << "first_height = " << first_height << std::endl;
    std::cerr << pad << "second_center = "; second_center.pinfo();
    std::cerr << pad << "second_base = " << second_base << std::endl;
    std::cerr << pad << "second_height = " << second_height << std::endl;
}

void MyGroup::WriteStructure(DTDataStorage &output,std::string name)
{
    // Structure for "input"
    output.Save("input",name+"_1N");
    output.Save("height",name+"_1T_1N");
    output.Save(1,name+"_1T_N");
    output.Save("Image",name+"_1T");

    // Structure for "first peak"
    output.Save("first peak",name+"_2N");
    output.Save("height",name+"_2T_1N");
    output.Save(1,name+"_2T_N");
    output.Save("Image",name+"_2T");

    // Structure for "first residual"
    output.Save("first residual",name+"_3N");
    output.Save("height",name+"_3T_1N");
    output.Save(1,name+"_3T_N");
    output.Save("Image",name+"_3T");

    // Structure for "second peak"
    output.Save("second peak",name+"_4N");
    output.Save("height",name+"_4T_1N");
    output.Save(1,name+"_4T_N");
    output.Save("Image",name+"_4T");

    // Structure for "second residual"
    output.Save("second residual",name+"_5N");
    output.Save("height",name+"_5T_1N");
    output.Save(1,name+"_5T_N");
    output.Save("Image",name+"_5T");

    // Structure for "first center"
    output.Save("first center",name+"_6N");
    output.Save("Point2D",name+"_6T");

    // Structure for "first base"
    output.Save("first base",name+"_7N");
    output.Save("Number",name+"_7T");

    // Structure for "first height"
    output.Save("first height",name+"_8N");
    output.Save("Number",name+"_8T");

    // Structure for "second center"
    output.Save("second center",name+"_9N");
    output.Save("Point2D",name+"_9T");

    // Structure for "second base"
    output.Save("second base",name+"_10N");
    output.Save("Number",name+"_10T");

    // Structure for "second height"
    output.Save("second height",name+"_11N");
    output.Save("Number",name+"_11T");

    output.Save(11,name+"_N");
    output.Save("MyGroup",name+"_Name");
    output.Save("Group",name);
}

void Write(DTDataStorage &output,std::string name,const MyGroup &var)
{
    Write(output,name+"_input",var.input);
    Write(output,name+"_first peak",var.first_peak);
    Write(output,name+"_first residual",var.first_residual);
    Write(output,name+"_second peak",var.second_peak);
    Write(output,name+"_second residual",var.second_residual);
    Write(output,name+"_first center",var.first_center);
    output.Save(var.first_base,name+"_first base");
    output.Save(var.first_height,name+"_first height");
    Write(output,name+"_second center",var.second_center);
    output.Save(var.second_base,name+"_second base");
    output.Save(var.second_height,name+"_second height");
    Write(output,name,DTDoubleArray());
}

void WriteOne(DTDataStorage &output,std::string name,const MyGroup &var)
{
    Write(output,name,var);
    output.Save("Group","Seq_"+name);
    MyGroup::WriteStructure(output,"SeqInfo_"+name);
}

void Read(DTDataStorage &input,std::string name,MyGroup &var)
{
    Read(input,name+"_input",var.input);
    Read(input,name+"_first peak",var.first_peak);
    Read(input,name+"_first residual",var.first_residual);
    Read(input,name+"_second peak",var.second_peak);
    Read(input,name+"_second residual",var.second_residual);
    Read(input,name+"_first center",var.first_center);
    var.first_base = input.ReadNumber(name+"_first base");
    var.first_height = input.ReadNumber(name+"_first height");
    Read(input,name+"_second center",var.second_center);
    var.second_base = input.ReadNumber(name+"_second base");
    var.second_height = input.ReadNumber(name+"_second height");
}
