// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#ifndef IT_computation_h
#define IT_computation_h

#include "structures.h"

#include "DTProgress.h"

DTImage Computation(DTPoint2D origin,double h,int m,int n,double radius,
                    const DTTable &points);

#endif /* IT_computation_h */ 
