// Auto-generated by ImageTank, can overwrite using the C++ template gear menu.

#include "computation.h"

#include "DTArguments.h"
#include "DTTimer.h"
#include "DTDataFile.h"
#include "DTError.h"

int main(int argc,const char *argv[])
{
    DTSetArguments(argc,argv);

    DTPoint2D origin;
    DTTable points;
    double h, radius;
    int m, n;

    {
        // Inside a scope so that the data files will be closed before the computation starts.
        DTDataFile inputDataFile("Input.dtbin",DTFile::ReadOnly);
        if (inputDataFile.IsOpen()==false) {
            std::cerr << "No input file found. Might have to save input for debugging." << std::endl;
        }
        DTDataFile variableDataFile;

        Read(inputDataFile,"origin",origin);
        h = inputDataFile.ReadNumber("h");
        m = inputDataFile.ReadNumber("m");
        n = inputDataFile.ReadNumber("n");
        radius = inputDataFile.ReadNumber("radius");
        variableDataFile = DTDataFile("points.dtbin",DTFile::ReadOnly);
        Read(variableDataFile,"points",points);
    }

    DTDataFile outputFile("Output.dtbin",DTFile::NewReadWrite);

    //DTTimer timer;
    //timer.Start();
    DTImage output = Computation(origin,h,m,n,radius,points);

    //timer.Stop(); // Use timer.Time() to get the elapsed time
    if (DTHowManyErrors()>0) outputFile.Save(DTHowManyErrors(),"ErrorCount"); // For error logging

    WriteOne(outputFile,"Var",output);
    // To speed up reading.
    outputFile.SaveIndex();

    return 0;
}
